meta:
  description: Quickly extract information from OP5 lic files.
  vendor: ITRS Group Ltd. <support@itrsgroup.com>
  maintainer: Johan Thorén, ITRS Group Ltd. <jthoren@itrsgroup.com>
  license: MIT
files:
  "/usr/bin/op5-license-inspector":
    file: op5-license-inspector-linux-x86_64
    mode: "0755"
    user: "root"
  "/usr/share/doc/op5-license-inspector/README.md":
    file: README.md
    mode: "0644"
    user: "root"
  "/usr/share/licenses/op5-license-inspector/LICENSE":
    file: LICENSE
    mode: "0644"
    user: "root"
